"""tools/build_dungeonquests.py: the quests of every dungeon for the addon's dungeon planner. The
reader of the hand-kept Forever data (its builder language run under lupa with stand-ins, on a
hand-made fixture in tools/tests/fixtures/att, no real data), the neutral form, the JSON input,
the empty file, the generated DungeonQuestData.lua (deterministic, valid Lua, in the TOC) and the
licence file that ships with it."""
import json
import os
import re
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
ROOT = os.path.dirname(TOOLS)
ADDON = os.path.join(ROOT, 'addon', 'Amisia')
FIXTURE = os.path.join(HERE, 'fixtures', 'att')
sys.path.insert(0, TOOLS)
import build_dungeonquests as bdq  # noqa: E402

FACTS = [
    {'key': 'thanes', 'name': 'Hall of Thanes', 'kind': 'party', 'min': 13, 'max': 18},
    {'key': 'deadmines', 'name': 'The Deadmines', 'kind': 'party'},
]


@pytest.fixture(scope='module')
def att():
    return bdq.read_att(FIXTURE, FACTS, 'abcdef0123456789')


def lua_load(text):
    from lupa.lua51 import LuaRuntime
    lua = LuaRuntime(unpack_returned_tuples=True)
    ns = lua.eval('{}')
    lua.eval('function(s) return assert(loadstring(s, "@DungeonQuestData.lua")) end')(text)('Amisia', ns)
    return ns.DUNGEON_QUESTS


def test_dungeon_quests_by_file_and_facts(att):
    data, report = att
    assert data['dungeons'] == {'thanes': [70001, 70002, 70003, 70004]}, data['dungeons']
    assert 'molten core' in report['instances without facts'], 'an instance without facts is reported, not invented'
    assert 70100 in data['quests'] and data['quests'][70100]['dungeon'] is None


def test_quest_fields(att):
    Q = att[0]['quests']
    q = Q[70001]
    assert q['name'] == 'First Grudge', 'the name from the comment, without the note after it'
    assert q['giver'] == 'Giver One', 'the giver from the comment, without the title'
    assert q['minLevel'] == 10 and q['level'] == 0 and q['faction'] == 'A'
    assert q['start'] == 'O' and q['points'] == [(1455, 3245, 4480)]
    assert q['rewards'] == [60001, 60002], 'the items of the quest, not the objective provider'
    assert set(q['preAll']) == {70010, 79999} and q['preOne'] == [70011, 70012]
    assert q['dungeon'] == 'thanes', 'the zone listing of the same quest does not take its dungeon'
    assert Q[70002]['start'] == 'I' and Q[70002]['faction'] == 'H', 'a giver on the dungeon map stands inside'
    assert Q[70003]['start'] == 'X' and Q[70003]['rewards'] == [60003], 'started by an item; a wrapper keeps its child'
    assert Q[70004]['start'] == '' and Q[70004]['points'] == [] and Q[70004]['giver'] == 'Lost Giver'
    assert Q[70011]['preAll'] == [70001] and Q[70011]['faction'] == 'H'
    assert bdq.clean_name('Name -- note') == 'Name' and bdq.clean_name('Name //x') == 'Name'


def test_render_keeps_dungeon_quests_and_their_pre_quests(att):
    data, _ = att
    text = bdq.render(data, '2026-10-06')
    assert text == bdq.render(data, '2026-10-06'), 'the same text twice'
    lines = text.split('\n')
    assert lines[0] == '-- GENERATED by tools/build_dungeonquests.py. Do not edit; rebuild instead.'
    assert 'MIT' in lines[1] and 'LICENSES' in lines[1] and 'abcdef0123' in lines[1]
    dq = lua_load(text)
    assert dq.D.thanes[1] == 70001 and dq.D.thanes[4] == 70004
    q = dq.Q[70001]
    assert q[1] == 'First Grudge' and q[2] == 10 and q[4] == 'A' and q[6] == 'O' and q[7] == 'Giver One'
    assert q[8] == '1455:3245:4480' and q[11] == 'thanes' and q[12][1] == 60001
    assert q[9][1] == 70010 and q[9][2] is None, 'a pre-quest without a record falls away'
    assert q[10][1] == 70011 and q[10][2] == 70012
    assert dq.Q[70010] is not None and dq.Q[70010][11] is None, 'a pre-quest has its own record'
    assert dq.Q[70500] is None and dq.Q[70100] is None, 'quests of no dungeon and no chain stay out'
    assert dq.Q[70003][7] is None and dq.Q[70003][8] is None
    assert bdq.ancestors(data['quests'], 70001)[:1] == [70010] and 70001 not in bdq.ancestors(data['quests'], 70001)


def test_json_input_and_the_empty_file(tmp_path):
    neutral = {'source': 'hand-made', 'commit': None, 'dungeons': {'deadmines': [5]},
               'quests': {'5': {'name': 'Hand Quest', 'minLevel': 15, 'level': 18, 'faction': '', 'classes': 1,
                                'start': 'O', 'giver': 'Hand', 'points': [[1436, 100, 200]], 'preAll': [], 'preOne': [],
                                'dungeon': 'deadmines', 'rewards': []}}}
    p = tmp_path / 'n.json'
    p.write_text(json.dumps(neutral), encoding='utf-8')
    dq = lua_load(bdq.render(bdq.read_json(str(p)), '2026-10-06'))
    assert dq.D.deadmines[1] == 5 and dq.Q[5][8] == '1436:100:200' and dq.Q[5][5] == 1 and dq.Q[5][3] == 18
    empty = lua_load(bdq.render(bdq.empty(), '2026-10-06'))
    assert next(iter(empty.D.items()), None) is None and next(iter(empty.Q.items()), None) is None


def test_shipped_file_loads_and_is_in_the_toc_with_its_licence():
    with open(os.path.join(ADDON, 'DungeonQuestData.lua'), encoding='utf-8') as fh:
        text = fh.read()
    assert text.startswith('-- GENERATED by tools/build_dungeonquests.py.')
    assert not re.search(r'[\x00-\x08\x0b-\x1f\x7f]', text)
    assert 'Questie' not in text, 'no data of other quest databases'
    with open(os.path.join(ADDON, 'Amisia.toc'), encoding='utf-8') as fh:
        toc = fh.read()
    assert '\nDungeonData.lua [AllowLoadGameType camelot]\nDungeonQuestData.lua [AllowLoadGameType camelot]\n' in toc
    with open(os.path.join(ADDON, 'LICENSES', 'AllTheThings-MIT.txt'), encoding='utf-8') as fh:
        lic = fh.read()
    assert 'Copyright (c) 2026 AllTheThings WoW Addon' in lic and 'Permission is hereby granted, free of charge' in lic
    dq = lua_load(text)
    facts = {e['key'] for e in bdq.load_facts()}
    for key, ids in dq.D.items():
        assert key in facts, key
        for i in ids.values():
            assert dq.Q[i] is not None and dq.Q[i][11] == key, (key, i)
    for qid, q in dq.Q.items():
        for field in (9, 10):
            for p in (q[field] or {}).values():
                assert dq.Q[p] is not None, ('pre-quest without a record', qid, p)


def test_the_downloaded_lua_runs_without_io_os_or_python(tmp_path):
    # the data files are third-party code: whatever they try, nothing outside the reader happens
    lua = bdq._att_lua()
    S = lua.execute(bdq.ATT_STUB)
    target = tmp_path / 'touched'
    for code in ['io.open(%r, "w"):write("x")', 'os.execute("touch " .. %r)',
                 'python.eval("open(%r, \'w\')")', 'loadstring("io.open(%r, [[w]])")()',
                 'require("os").execute("touch " .. %r)', 'getfenv(0).io.open(%r, "w")',
                 'rawget(_G, "io").open(%r, "w")']:
        try:
            S.run(code % str(target), 'evil.lua')
        except Exception:
            pass
        assert not target.exists(), code
    assert lua.eval('io') is None and lua.eval('os') is None and lua.eval('python') is None
