"""tools/build_map.py: reading the public quest database's Lua tables, turning spawns into map points,
resolving every source kind to a place and writing MapData.lua / MapDataTBC.lua."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
import build_map  # noqa: E402

NPCS = r"""-- AUTO GENERATED FILE! DO NOT EDIT!
local QuestieDB = QuestieLoader:ImportModule("QuestieDB");
QuestieDB.npcKeys = {
    ['name'] = 1, -- string
}
QuestieDB.npcData = [[return {
[100] = {'Marshal McBride',1,1,10,10,0,{[12]={{42.32,65.10}}},nil,12,{7},nil,11,"A",nil,2},
[101] = {'Gorn One Eye',1,1,30,30,0,{[361]={{47.2,33.1}}},nil,361,nil,nil,29,"H","Armorer",4},
[102] = {'Gorn One Eye',1,1,30,30,0,{[14]={{10,10}}},nil,14,nil,nil,29,"H",nil,4},
[103] = {'Muad',1,1,10,10,4,{[85]={{35.1,55.2},{35.15,55.25},{38.2,50.1},{90,90},{10,90},{90,10}}},nil,85,nil,nil,14,nil,nil,0},
[104] = {'Edwin VanCleef',1,1,21,21,1,{[1581]={{-1,-1}}},nil,1581,nil,nil,14,nil,nil,0},
[105] = {'Quartermaster Urgronn',1,1,70,70,0,{[3483]={{54.9,37.8}}},nil,3483,nil,nil,1,"H","Thrallmar Quartermaster",4},
[106] = {'Okuno',1,1,70,70,0,{[3959]={{60,60}}},nil,3959,nil,nil,1,"AH","Ashtongue Deathsworn Quartermaster",4},
[107] = {'Jho\'nass',1,1,70,70,0,{[3522]={{28.0,58.0}}},nil,3522,nil,nil,1,"AH","Ogri'la Quartermaster",4},
[108] = {'Archmage Leryda',1,1,70,70,0,{[41]={{47.0,75.6}}},nil,41,nil,nil,1,"AH",nil,4},
[109] = {'Wanderer',1,1,10,10,0,{[9999]={{1,1}},[12]={{-1,-1}}},nil,12,nil,nil,1,nil,nil,0},
[110] = {'Twin',1,1,10,10,0,{[12]={{20,20}}},nil,12,nil,nil,1,nil,nil,0},
[111] = {'Twin',1,1,10,10,0,{[361]={{30,30}}},nil,361,nil,nil,1,nil,nil,0},
}]]
"""

OBJECTS = r"""QuestieDB.objectData = [[return {
[500] = {'Wanted Poster',{8},nil,{[12]={{50.5,50.5}}},12,0},
}]]
"""

QUESTS = r"""QuestieDB.questData = [[return {
[7] = {'Kobold Camp Cleanup',{{100}},{{100}},1,2,77,nil},
[8] = {'A Poster',{nil,{500}},nil,1,2,77,nil},
[9] = {'Item Start',{nil,nil,{1234}},nil,1,2,77,nil},
}]]
"""

AREAS = r"""local ZoneDB = QuestieLoader:ImportModule("ZoneDB")
ZoneDB.private.areaIdToUiMapIdOverride = [[return {
    [0] = 0, -- fail-safe
    [99] = 6,
    [361] = 1448,
}]]
ZoneDB.private.areaIdToUiMapId = [[return {
    [12] = 1429,
    [14] = 1411,
    [40] = 1436,
    [41] = 1430,
    [85] = 1420,
    [99] = 5,
    [361] = 1,
    [3483] = 1944,
    [3520] = 1948,
    [3522] = 1949,
    [1581] = 291,
}]]
"""

DUNGEONS = r"""local ZoneDB = QuestieLoader:ImportModule("ZoneDB")
local Expansions = QuestieLoader:ImportModule("Expansions")
local isHorde = UnitFactionGroup("Player") == "Horde"
local dungeons = {
    [1581] = {"The Deadmines",{10029},40,{{40, 42.5, 71.7}}},
    [3457] = {"Karazhan",{10103},41,{{41, 46.7, 70.2},{41, 46.9, 74.7}}},
    [3959] = {"Black Temple",nil,3520,{{3520, 71, 46.4}}},
    [3607] = {"Serpentshire Cavern",nil,3521,{{3521, 50.4, 40.9}}},
    [2597] = {"Alterac Valley",nil,36,{(isHorde and {36, 39.5, 80.2}) or {36, 63.6, 58.8}}},
}
if Expansions.Current >= Expansions.Tbc then
    dungeons[1581][4] = {{40, 42.6, 71.8}} -- The Deadmines
end
if Expansions.Current >= Expansions.Wotlk then
    dungeons[3457][4] = {{41, 1, 1}} -- Karazhan
end
ZoneDB.private.dungeons = dungeons
"""

INSTANCES = r"""local ZoneDB = QuestieLoader:ImportModule("ZoneDB")
ZoneDB.instanceIdToAreaId = {
    [36] = ZoneDB.zoneIDs.THE_DEADMINES,
    [532] = ZoneDB.zoneIDs.KARAZHAN,
    [548] = ZoneDB.zoneIDs.SERPENTSHRINE_CAVERN,
    [999] = ZoneDB.zoneIDs.NOWHERE,
}
"""

TEXTS = {'npc': NPCS, 'object': OBJECTS, 'quest': QUESTS, 'area': AREAS, 'dungeons': DUNGEONS, 'instance': INSTANCES}

GEAR_FOREVER = r"""-- GENERATED by tools/build_gear.py. Do not edit; rebuild instead.
local _, ns = ...
ns.GEAR = {
    built = "2026-10-04",
    S = {
        {"Q", "Kobold Camp Cleanup", 2, 1, "A", 1429, 7, 0},
        {"Q", "A Poster", 2, 1, "A", 1429, 8, 0},
        {"Q", "Item Start", 2, 1, "A", 1429, 9, 0},
        {"Q", "Dungeon quest without id", 20, 15, nil, nil, nil, 0, "The Deadmines"},
        {"V", "Gorn One Eye", 1448},
        {"V", "Gorn One Eye", 1448, "H", "Armorer"},
        {"P", "Gorn One Eye", 1448, "H", "Armorer", nil, 101},
        {"R", "Muad", 10, 1420},
        {"R", "Muad", 10, 1420, 103},
        {"W", "Trash (The Deadmines)", 18, 19},
        {"W", "Wanderer", 10, 10, 1429},
        {"W", "Twin", 10, 10},
        {"W", "Twin", 10, 10, 1411},
        {"W", nil, 10, 20},
        {"D", "Deadmines", "Cookie", nil, 291},
        {"X", "Karazhan", "Prince", 532, 3457, 1, 0},
        {"C", "tailoring", 50},
        {"A"},
    },
    Z = {},
    I = {
        [1] = {"HEAD", 4, 1, 1, 2, 1, 5, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18},
    },
}
"""

GEAR_TBC = r"""local _, ns = ...
if ns.IsForever and ns.IsForever() then return end
ns.GEAR = {
    game = "tbc", cap = 70, built = "2026-10-05",
    S = {
        {"D", "The Deadmines", "Cookie", nil, 36, 1581, 0},
        {"X", "Black Temple", "Supremus", 564, 3959, 3, 0},
        {"X", "Serpentshrine Cavern", "Lurker", 548, 0, 2, 0},
        {"F", "Thrallmar", 5, 947, "H"},
        {"F", "Ogri'la", 5, 1038, ""},
        {"F", "Ashtongue Deathsworn", 8, 1012, ""},
        {"F", "Tranquillien", 5, 922, "H"},
        {"V", "G'eras", 111, "", "Abzeichen der Gerechtigkeit", 1},
        {"W", nil, 70, 73, 0},
    },
    Z = {},
    I = {},
}
"""


def write(tmp_path, name, text):
    p = tmp_path / name
    p.write_text(text, encoding='utf-8')
    return str(p)


def parsed(game='forever', gear=GEAR_FOREVER, tmp_path=None):
    recs, has_game = build_map.load_gear_text(gear, game)
    needed = build_map.needed_keys(recs, has_game)
    return build_map.parse_questie(TEXTS, game, needed), needed


# ---------------------------------------------------------------- reading the Lua tables
def test_return_blocks_are_found_and_read():
    blocks = build_map.return_blocks(AREAS)
    assert set(blocks) == {'ZoneDB.private.areaIdToUiMapIdOverride', 'ZoneDB.private.areaIdToUiMapId'}
    t = build_map.read_table(blocks['ZoneDB.private.areaIdToUiMapId'])
    assert t[12] == 1429 and t[99] == 5
    npcs = build_map.read_table(build_map.return_blocks(NPCS)['QuestieDB.npcData'])
    assert npcs[107][1] == "Jho'nass" and npcs[103][7][85][2] == {1: 35.15, 2: 55.25}


def test_area_table_overrides_win_and_zero_drops():
    areas = build_map.area_to_ui(AREAS)
    assert areas[99] == 6 and areas[361] == 1448 and areas[12] == 1429
    assert 0 not in areas


def test_dungeons_take_the_corrections_of_their_expansion():
    tbc = build_map.read_dungeons(DUNGEONS, build_map.EXPANSION['tbc'])
    era = build_map.read_dungeons(DUNGEONS, build_map.EXPANSION['forever'])
    assert era[1581]['entrances'] == [(40, 42.5, 71.7)], 'Forever is Era: no TBC correction'
    assert tbc[1581]['entrances'] == [(40, 42.6, 71.8)], 'the TBC correction line wins'
    assert tbc[3457]['entrances'] == [(41, 46.7, 70.2), (41, 46.9, 74.7)], 'Karazhan keeps both entrances, no Wotlk line'
    assert tbc[1581]['alt'] == [10029] and tbc[1581]['name'] == 'The Deadmines'
    assert tbc[2597]['entrances'] == [(36, 63.6, 58.8)]


def test_instances_resolve_by_dungeon_name():
    d = build_map.read_dungeons(DUNGEONS, 2)
    inst, unknown = build_map.read_instances(INSTANCES, d)
    assert inst == {36: 1581, 532: 3457, 548: 3607}
    assert unknown == ['NOWHERE']


# ---------------------------------------------------------------- points
def test_spawns_become_points_in_hundredths():
    areas = build_map.area_to_ui(AREAS)
    dungeons = build_map.read_dungeons(DUNGEONS, 2)
    unknown = set()
    pts = build_map.spawn_points({12: [[42.326, 65.104], [-1, -1]], 9999: [[1, 1]]}, areas, dungeons, unknown)
    assert pts == [(1429, 4233, 6510)], 'rounded, -1/-1 and unknown areas dropped'
    assert unknown == {9999}
    inside = build_map.spawn_points({3959: [[60, 60]], 10029: [[-1, -1]]}, areas, dungeons, unknown)
    assert inside == [(1948, 7100, 4640), (1436, 4260, 7180)], 'inside an instance: its entrance'


def test_at_most_four_points_far_apart():
    pts = [(1, 3510, 5520), (1, 3515, 5525), (1, 3820, 5010), (1, 9000, 9000), (1, 1000, 9000), (1, 9000, 1000)]
    picked = build_map.pick_points(pts)
    assert len(picked) == 4
    assert (1, 3515, 5525) not in picked, 'the near twin within 2 % is merged'
    assert {(1, 9000, 9000), (1, 1000, 9000), (1, 9000, 1000)} <= set(picked)
    assert build_map.pick_points([(1, 10, 10), (2, 10, 10)]) == [(1, 10, 10), (2, 10, 10)], 'other maps always count'
    assert build_map.fmt_points([(1429, 4232, 6510), (1, 0, 10000)]) == '1429:4232:6510 1:0:10000'


# ---------------------------------------------------------------- keys
def test_keys_per_source_kind():
    k = build_map.key_of
    assert k(['Q', 'x', 1, 1, 'A', 1429, 7, 0], False) == 'Q:7'
    assert k(['Q', 'x', 1, 1, None, None, None, 0, 'Dungeon'], False) is None
    assert k(['V', 'Gorn One Eye', 1448], False) == 'V:Gorn One Eye'
    assert k(['P', 'Gorn One Eye', 1448, 'H', 'Armorer', None, 101], False) == 'U:101'
    assert k(['V', 'Gorn One Eye', 1448, 'H', 'Armorer', None, 101], False) == 'U:101'
    assert k(['R', 'Muad', 10, 1420], False) == 'R:Muad' and k(['R', 'Muad', 10, 1420, 103], False) == 'U:103'
    assert k(['W', 'Trash (The Deadmines)', 18, 19], False) == 'N:The Deadmines'
    assert k(['W', 'Twin', 10, 10, 1411], False) == 'W:Twin' and k(['W', 'Twin', 10, 10, None, 111], False) == 'U:111'
    assert k(['W', 'Twin', 10, 10], False) is None, 'a named mob without zone has no place'
    assert k(['W', None, 10, 20], False) is None
    assert k(['D', 'Deadmines', 'Cookie', None, 291], False) == 'N:Deadmines', 'old Forever data: by name'
    assert k(['D', 'The Deadmines', 'Cookie', None, 36, 1581, 0], True) == 'I:36'
    assert k(['X', 'Karazhan', 'Prince', 532, 3457, 1, 0], False) == 'I:532'
    assert k(['F', 'Thrallmar', 5, 947, 'H'], True) == 'F:947'
    assert k(['C', 'tailoring', 50], False) is None and k(['A'], False) is None


def test_gear_data_is_read_through_its_guard():
    recs, has_game = build_map.load_gear_text(GEAR_FOREVER, 'forever')
    assert not has_game and recs[0] == ['Q', 'Kobold Camp Cleanup', 2, 1, 'A', 1429, 7, 0]
    assert recs[6] == ['P', 'Gorn One Eye', 1448, 'H', 'Armorer', None, 101]
    recs, has_game = build_map.load_gear_text(GEAR_TBC, 'tbc')
    assert has_game and recs[3] == ['F', 'Thrallmar', 5, 947, 'H']


# ---------------------------------------------------------------- resolving
def test_quests_by_npc_and_object_and_item_starters():
    subset, needed = parsed()
    P, G, report = build_map.resolve(subset, needed, 'forever')
    assert P['Q:7'] == [(1429, 4232, 6510)] and G['Q:7'] == 'Marshal McBride'
    assert P['Q:8'] == [(1429, 5050, 5050)] and 'Q:8' not in G, 'object starter, no giver name'
    assert P['Q:9'] == [] and report['quest item start'] == 1


def test_vendors_by_name_prefer_their_zone_and_npc_ids_win():
    subset, needed = parsed()
    P, G, report = build_map.resolve(subset, needed, 'forever')
    assert P['V:Gorn One Eye'] == [(1448, 4720, 3310)], 'the one in the source zone'
    assert P['U:101'] == [(1448, 4720, 3310)]
    assert len(P['R:Muad']) == 4 and P['R:Muad'] == P['U:103']
    assert P['N:The Deadmines'] == [(1436, 4250, 7170)] and P['N:Deadmines'] == P['N:The Deadmines']
    assert P['I:532'] == [(1430, 4670, 7020), (1430, 4690, 7470)], 'by the record area: two entrances'
    assert P['W:Wanderer'] == [], 'only spawns in unknown areas'
    assert report['unknown areas'] == [9999]
    assert set(P['W:Twin']) == {(1429, 2000, 2000), (1448, 3000, 3000)}
    assert report['ambiguous'] == ['W:Twin'], 'two Twins, none in the source zone'


def test_quartermasters_and_entrances_on_tbc():
    subset, needed = parsed('tbc', GEAR_TBC)
    P, G, report = build_map.resolve(subset, needed, 'tbc')
    assert P['F:947'] == [(1944, 5490, 3780)] and G['F:947'] == 'Quartermaster Urgronn'
    assert P['F:1038'] == [(1949, 2800, 5800)] and G['F:1038'] == "Jho'nass"
    assert P['F:1012'] == [(1948, 7100, 4640)], 'Okuno stands in Black Temple: its entrance'
    assert P['F:922'] == [] and report['factions without quartermaster'] == [922]
    assert P['I:36'] == [(1436, 4260, 7180)], 'with the TBC correction'
    assert P['I:564'] == [(1948, 7100, 4640)]
    assert P['I:548'] == [], 'the entrance zone has no map: counted, not invented'
    assert report['kinds']['F'] == (3, 1)


def test_every_quartermaster_is_one():
    npcs = build_map.read_table(build_map.return_blocks(NPCS)['QuestieDB.npcData'])
    by_name = {row[1]: row for row in npcs.values()}
    checked = 0
    for fid, name in build_map.QUARTERMASTERS.items():
        row = by_name.get(name)
        if row is None:
            continue
        checked += 1
        assert 'Quartermaster' in (row.get(14) or '') or name in build_map.QUARTERMASTER_EXCEPTIONS, name
    assert checked == 4


def test_the_real_quartermasters_stand_in_the_data():
    path = build_map.MAP_JSON
    if not os.path.exists(path):
        return
    with open(path, encoding='utf-8') as fh:
        data = json.load(fh)
    npcs = data['tbc']['npcs']
    names = {v[0]: v for v in npcs.values()}
    for fid, name in build_map.QUARTERMASTERS.items():
        assert name in names, name
        assert 'Quartermaster' in (names[name][2] or '') or name in build_map.QUARTERMASTER_EXCEPTIONS, name


# ---------------------------------------------------------------- output
def test_output_header_guard_sorted_and_repeatable(tmp_path):
    subset, needed = parsed()
    P, G, _ = build_map.resolve(subset, needed, 'forever')
    out = tmp_path / 'MapData.lua'
    build_map.write_lua(str(out), 'forever', P, G, '9d39232dab48e35811a7cc02473c2f4e42b62ab6', '2026-10-05')
    text = out.read_text(encoding='utf-8')
    lines = text.split('\n')
    assert lines[0] == '-- GENERATED by tools/build_map.py. Do not edit; rebuild instead.'
    assert '(' + build_map.QUESTIE_LICENSE + ')' in lines[1] and 'QuestieDB' in lines[1] and '9d39232dab' in lines[1]
    assert lines[2] == 'local _, ns = ...' and lines[3] == 'if not (ns.IsForever and ns.IsForever()) then return end'
    assert '    game = "forever", built = "2026-10-05", questie = "9d39232dab",' in lines
    keys = [ln.split('"')[1] for ln in lines if ln.startswith('        ["')]
    pkeys = keys[:len([k for k in P if P[k]])]
    assert pkeys == sorted(pkeys)
    assert '["W:Wanderer"]' not in text, 'keys without points stay out'
    assert '["Q:7"] = "1429:4232:6510",' in text
    first = text
    build_map.write_lua(str(out), 'forever', P, G, '9d39232dab48e35811a7cc02473c2f4e42b62ab6', '2026-10-05')
    assert out.read_text(encoding='utf-8') == first

    from lupa.lua51 import LuaRuntime
    lua = LuaRuntime(unpack_returned_tuples=True)
    chunk = lua.eval('function(s) return assert(loadstring(s, "@MapData.lua")) end')(text)
    ns = lua.eval('{ IsForever = function() return true end }')
    chunk('Amisia', ns)
    assert ns.MAP.P['Q:7'] == '1429:4232:6510' and ns.MAP.G['Q:7'] == 'Marshal McBride' and ns.MAP.game == 'forever'
    ns2 = lua.eval('{ IsForever = function() return false end }')
    chunk('Amisia', ns2)
    assert ns2.MAP is None, 'the guard keeps it off TBC'

    tout = tmp_path / 'MapDataTBC.lua'
    sub, need = parsed('tbc', GEAR_TBC)
    P2, G2, _ = build_map.resolve(sub, need, 'tbc')
    build_map.write_lua(str(tout), 'tbc', P2, G2, 'abc', '2026-10-05')
    tl = tout.read_text(encoding='utf-8').split('\n')
    assert tl[3] == 'if ns.IsForever and ns.IsForever() then return end'


def test_only_needed_keys_and_offline_subset_gives_the_same(tmp_path):
    subset, needed = parsed()
    P, G, _ = build_map.resolve(subset, needed, 'forever')
    assert set(P) == set(needed)
    again = json.loads(json.dumps(subset))
    P2, G2, _ = build_map.resolve(again, needed, 'forever')
    assert P2 == P and G2 == G, 'the subset kept in map_questie.json builds the same'
    assert 'Marshal McBride' in json.dumps(subset) and 'Okuno' not in json.dumps(subset), 'only what the data needs'
