"""tools/build_dungeonart.py: the client's own loading screen per dungeon (client tables Map and
LoadingScreens), the snapshot tools/forever_dungeon_art.json and the generated DungeonArt.lua
(current, deterministic, valid Lua, in the TOC before the planner)."""
import json
import os
import re
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
ROOT = os.path.dirname(TOOLS)
ADDON = os.path.join(ROOT, 'addon', 'Amisia')
sys.path.insert(0, TOOLS)
import build_dungeonart  # noqa: E402

OUT = os.path.join(ADDON, 'DungeonArt.lua')
SNAPSHOT = os.path.join(TOOLS, 'forever_dungeon_art.json')

MAP_HEAD = 'ID,Directory,MapName_lang,InstanceType,LoadingScreenID\n'
LS_HEAD = ('ID,NarrowScreenFileDataID,WideScreenFileDataID,WideScreen169FileDataID,LoadingScreenSkinID,'
           'MainImageFileDataID,LogoFileDataID\n')


def write_tables(folder, maps, screens, build='1.60.1.70235'):
    folder.mkdir(parents=True, exist_ok=True)
    (folder / f'Map.{build}.csv').write_text(MAP_HEAD + ''.join(f'{a},{b},{c},{d},{e}\n' for a, b, c, d, e in maps),
                                              encoding='utf-8')
    (folder / f'LoadingScreens.{build}.csv').write_text(
        LS_HEAD + ''.join(f'{a},{b},0,0,{c},{d},0\n' for a, b, c, d in screens), encoding='utf-8')


FACTS = [
    {'key': 'deadmines', 'name': 'The Deadmines', 'kind': 'party', 'inst': 36},
    {'key': 'lordaeron', 'name': 'Ruins of Lordaeron', 'kind': 'party', 'inst': 2999},
    {'key': 'lbrs', 'name': 'Lower Blackrock Spire', 'kind': 'party', 'inst': 229},
    {'key': 'ubrs', 'name': 'Upper Blackrock Spire', 'kind': 'party', 'inst': 229},
    {'key': 'drowned', 'name': 'Drowned City', 'kind': 'party'},
    {'key': 'nofile', 'name': 'Has No File', 'kind': 'party', 'inst': 77},
    {'key': 'onyxia', 'name': "Onyxia's Lair", 'kind': 'raid', 'inst': 249},
]
MAPS = [(36, 'DeadminesInstance', 'Deadmines', 1, 142), (2999, '2999', 'Ruins of Lordaeron', 1, 650),
        (229, 'BlackRockSpire', 'Blackrock Spire', 1, 189), (77, 'X', 'Has No File', 1, 999),
        (249, 'OnyxiaLairInstance', "Onyxia's Lair", 2, 61), (35, 'StormwindPrison', '<unused>', 0, 23)]
SCREENS = [(142, 131833, 0, 0), (650, 0, 11, 7963782), (189, 131825, 0, 0), (61, 131863, 0, 0), (23, 131838, 0, 0),
           (999, 0, 0, 0)]


def test_art_per_dungeon_from_map_and_loading_screens(tmp_path):
    write_tables(tmp_path / 'wago', MAPS, SCREENS)
    art = build_dungeonart.client_art(FACTS, [str(tmp_path / 'wago')])
    assert art['tables'] == {'Map': 'Map.1.60.1.70235.csv', 'LoadingScreens': 'LoadingScreens.1.60.1.70235.csv'}
    assert art['build'] == '1.60.1.70235'
    d = art['dungeons']
    assert d['deadmines'] == [131833, 'n'], 'a classic 4:3 screen (square texture)'
    assert d['lordaeron'] == [7963782, 'w'], "Forever's own wide screens"
    assert d['lbrs'] == d['ubrs'] == [131825, 'n'], 'both halves of one instance'
    assert 'drowned' not in d, 'no instance id: the fallback'
    assert 'nofile' not in d, 'a loading screen row without a file: the fallback'
    assert d['onyxia'] == [131863, 'n']
    # the fallbacks: the client's general dungeon and raid screens, as its Map table uses them
    assert art['party'] == [131838, 'n'] and art['raid'] == [131863, 'n']


def test_missing_tables_give_nothing(tmp_path):
    art = build_dungeonart.client_art(FACTS, [str(tmp_path / 'none')])
    assert art['dungeons'] == {} and art['tables'] == {}


def test_a_later_folder_fills_a_table_the_first_lacks(tmp_path):
    write_tables(tmp_path / 'b', MAPS, SCREENS)
    (tmp_path / 'a').mkdir()
    (tmp_path / 'a' / 'Map.1.60.1.70235.csv').write_text(MAP_HEAD + '36,D,Deadmines,1,142\n', encoding='utf-8')
    art = build_dungeonart.client_art(FACTS, [str(tmp_path / 'a'), str(tmp_path / 'b')])
    assert art['dungeons']['deadmines'] == [131833, 'n']
    assert 'lordaeron' not in art['dungeons'], "the first folder's Map wins"


def test_render_is_lua_with_the_fallbacks():
    art = {'build': '1.60.1.70235', 'tables': {}, 'party': [131838, 'n'], 'raid': [131863, 'n'],
           'dungeons': {'wc': [131882, 'n'], 'thanes': [7963781, 'w']}}
    text = build_dungeonart.render(art)
    assert text.startswith('-- GENERATED by tools/build_dungeonart.py')
    assert 'ns.DUNGEON_ART = {' in text
    assert '        thanes = { 7963781, "w" },' in text and text.index('thanes') < text.index('wc =')
    assert '    party = { 131838, "n" },' in text and '    raid = { 131863, "n" },' in text


def snapshot():
    with open(SNAPSHOT, encoding='utf-8') as fh:
        return json.load(fh)


def test_the_snapshot_covers_the_dungeons_the_client_has():
    s = snapshot()
    d = s['dungeons']
    for key in ('rfc', 'wc', 'deadmines', 'thanes', 'sfk', 'lordaeron', 'bfd', 'stockade', 'gnomer', 'rfk',
                'excavation', 'dalaran', 'sm', 'rfd', 'ulda', 'zf', 'mara', 'brd', 'lbrs', 'ubrs', 'dire', 'scholo',
                'strat', 'onyxia'):
        assert key in d, key
        fid, kind = d[key]
        assert isinstance(fid, int) and fid > 0 and kind in ('n', 'w'), (key, d[key])
    assert d['thanes'][1] == 'w' and d['deadmines'] == [131833, 'n']
    assert s['party'][0] > 0 and s['raid'][0] > 0


def test_the_generated_file_is_current_and_deterministic():
    one = build_dungeonart.render(snapshot())
    assert one == build_dungeonart.render(snapshot())
    with open(OUT, encoding='utf-8') as fh:
        assert fh.read() == one, 'DungeonArt.lua is behind: python tools/build_dungeonart.py'
    one.encode('ascii')


def test_the_generated_file_is_valid_lua():
    lupa = pytest.importorskip('lupa.lua51')
    lua = lupa.LuaRuntime(unpack_returned_tuples=True)
    ns = lua.eval('{}')
    with open(OUT, encoding='utf-8') as fh:
        chunk = lua.eval('function(s) return assert(loadstring(s)) end')(fh.read())
    chunk('Amisia', ns)
    a = ns.DUNGEON_ART
    assert a.D.deadmines[1] == 131833 and a.D.deadmines[2] == 'n'
    assert a.party[1] > 0 and a.raid[1] > 0


def test_the_toc_loads_the_art_on_forever_before_the_planner():
    with open(os.path.join(ADDON, 'Amisia.toc'), encoding='utf-8') as fh:
        lines = [l.strip() for l in fh if l.strip() and not l.startswith('#')]
    assert 'DungeonArt.lua [AllowLoadGameType camelot]' in lines
    names = [re.sub(r'\s*\[.*\]', '', l) for l in lines]
    assert names.index('DungeonData.lua') < names.index('DungeonArt.lua') < names.index('Dungeons.lua')
