"""tools/build_quests.py: every quest of WoW Forever for the addon's quest tracker. The reader (the
hand-made fixture in tools/tests/fixtures/att through tools/att_data.py, with the quest folders),
the neutral form, the compact output (one string per quest, an NPC table for the givers, English
zone names as the fallback), its determinism and size, the empty file, the TOC and the licence."""
import os
import re
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
ROOT = os.path.dirname(TOOLS)
ADDON = os.path.join(ROOT, 'addon', 'Amisia')
FIXTURE = os.path.join(HERE, 'fixtures', 'att')
sys.path.insert(0, TOOLS)
import build_quests as bq  # noqa: E402


@pytest.fixture(scope='module')
def att():
    return bq.read_att(FIXTURE, 'abcdef0123456789')


def lua_load(text):
    from lupa.lua51 import LuaRuntime
    lua = LuaRuntime(unpack_returned_tuples=True)
    ns = lua.eval('{}')
    lua.eval('function(s) return assert(loadstring(s, "@QuestData.lua")) end')(text)('Amisia', ns)
    return ns.QUEST_DATA


def fields(qd, qid):
    return qd.Q[qid].split(';')


def test_every_quest_of_the_data(att):
    data, report = att
    Q = data['quests']
    for qid in (70001, 70010, 71001, 71004, 72001, 72003, 72100):
        assert qid in Q, qid
    assert 71002 not in Q and 71003 not in Q, 'not in Forever'
    assert report['quests'] == len(Q)


def test_quest_fields(att):
    Q, N = att[0]['quests'], att[0]['npcs']
    q = Q[71001]
    assert q['name'] == 'Boar Trouble' and q['zone'] == 1426 and q['minLevel'] == 6 and q['faction'] == 'A'
    assert q['classes'] == 3 and q['races'] == 1 | 4 and q['giver'] == 81001 and q['start'] == 'O'
    assert q['rewards'] == [61001], 'gear only: the satchel and the ring the item export does not know stay out'
    assert q['points'] == [], 'the giver stands where the quest starts: its points live with the NPC'
    assert N[81001]['name'] == 'Farmer Fixture' and (1426, 4000, 6000) in N[81001]['points']
    q = Q[72002]
    assert q['pre'] == [72001] and q['rewards'] == [61090] and q['start'] == 'O', 'the giver has points from 72001'
    assert q['zone'] == 1426 and q['classes'] == 4 and q['races'] == 8
    assert Q[72003]['skill'] == 171 and Q[72003]['zone'] == 1426
    assert Q[72004]['breadcrumb'] and Q[72004]['repeatable']
    assert Q[72005]['alt'] == [72006] and Q[72006]['alt'] == [72005]
    assert Q[72100]['old'] and Q[72100]['skill'] == 164 and Q[72100]['zone'] == 1455, 'no zone header: the point decides'
    assert Q[71004]['giver'] == 0 and Q[71004]['points'] == [(1426, 1000, 1000), (1455, 2000, 2000)]
    assert Q[70003]['start'] == 'X' and Q[70003]['giver'] == 0, 'started by an item'


def test_render(att):
    data = att[0]
    text = bq.render(data, '2026-10-06')
    assert text == bq.render(data, '2026-10-06'), 'the same text twice'
    lines = text.split('\n')
    assert lines[0] == '-- GENERATED by tools/build_quests.py. Do not edit; rebuild instead.'
    assert 'MIT' in lines[1] and 'LICENSES' in lines[1] and 'abcdef0123' in lines[1]
    qd = lua_load(text)
    assert qd.built == '2026-10-06' and qd.count == len(data['quests'])
    f = fields(qd, 71001)
    assert len(f) == 14
    assert f[:9] == ['1426', 'Boar Trouble', '6', 'A', '3', '5', '0', '81001', '']
    assert f[9:] == ['O', '', '', '61001', '']
    f = fields(qd, 72002)
    assert f[10] == '72001' and f[12] == '61090'
    assert fields(qd, 72004)[13] == 'BR' and fields(qd, 72100)[13] == 'C'
    assert fields(qd, 72005)[11] == '72006' and fields(qd, 72005)[6] == '164'
    assert fields(qd, 71004)[8] == '1426:1000:1000 1455:2000:2000'
    assert qd.N[81001] == 'Farmer Fixture;1426:4000:6000', qd.N[81001]
    assert qd.Z[1426] == 'Test Hills' and qd.Z[1455] == 'Test City'


def test_names_with_the_separator_stay_one_field():
    data = bq.empty()
    data['quests'][5] = dict(bq.QUEST_DEFAULTS, name='A; B "quoted"', zone=1, giver=7)
    data['npcs'][7] = {'name': 'Gi;ver', 'points': []}
    qd = lua_load(bq.render(data, 'x'))
    assert fields(qd, 5)[1] == 'A, B "quoted"' and qd.N[7] == 'Gi,ver;'


def test_pre_quests_without_a_record_fall_away():
    data = bq.empty()
    data['quests'][5] = dict(bq.QUEST_DEFAULTS, name='A', pre=[6, 99], alt=[98])
    data['quests'][6] = dict(bq.QUEST_DEFAULTS, name='B')
    qd = lua_load(bq.render(data, 'x'))
    assert fields(qd, 5)[10] == '6' and fields(qd, 5)[11] == ''


def test_any_one_of_the_pre_quests_and_no_self_pre():
    f = fields(lua_load(bq.render(bq.read_att(FIXTURE)[0], 'x')), 72007)
    assert f[10] == '72005,72006' and f[13] == 'N1', 'sourceQuestNumRequired 1: the flag N1'
    data = bq.empty()
    data['quests'][5] = dict(bq.QUEST_DEFAULTS, name='A', pre=[5, 6, 7], sqreq=1)
    data['quests'][6] = dict(bq.QUEST_DEFAULTS, name='B', pre=[6])
    data['quests'][7] = dict(bq.QUEST_DEFAULTS, name='C', pre=[6, 8], sqreq=2)
    qd = lua_load(bq.render(data, 'x'))
    assert fields(qd, 5)[10] == '6,7' and fields(qd, 5)[13] == 'N1', 'a quest is no pre-quest of itself'
    assert fields(qd, 6)[10] == '' and fields(qd, 6)[13] == ''
    assert fields(qd, 7)[10] == '6' and fields(qd, 7)[13] == '', 'as many needed as known: all of them, no flag'


def test_empty_file_loads():
    qd = lua_load(bq.render(bq.empty(), 'x'))
    assert qd.count == 0 and qd.source == 'none yet'


def test_the_shipped_file():
    path = os.path.join(ADDON, 'QuestData.lua')
    with open(path, encoding='utf-8') as fh:
        text = fh.read()
    assert text.startswith('-- GENERATED by tools/build_quests.py')
    assert os.path.getsize(path) < 600 * 1024, 'kept small: one string per quest'
    qd = lua_load(text)
    assert qd.count >= 0
    with open(os.path.join(ADDON, 'Amisia.toc'), encoding='utf-8') as fh:
        toc = fh.read()
    assert re.search(r'^QuestData\.lua \[AllowLoadGameType camelot\]$', toc, re.M)
    assert toc.index('QuestData.lua') < toc.index('Quests.lua') < toc.index('Pages\\Quests.lua')
    with open(os.path.join(ADDON, 'LICENSES', 'AllTheThings-MIT.txt'), encoding='utf-8') as fh:
        assert 'QuestData.lua' in fh.read()
