"""tools/build_magescrolls.py: the mage scrolls (Comprehension) from the client tables (hand-made
fixture CSVs in tests/fixtures/wago_magescrolls, not real data) and the AllTheThings fixture (the
library books, a world drop), and the generated addon/Amisia/Data/MageScrollData.lua (valid Lua,
lazy, in the TOC before the scrolls page)."""
import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
ROOT = os.path.dirname(TOOLS)
ADDON = os.path.join(ROOT, 'addon', 'Amisia')
sys.path.insert(0, TOOLS)
import att_data  # noqa: E402
import build_magescrolls  # noqa: E402
import lua_data  # noqa: E402

FIX = os.path.join(HERE, 'fixtures', 'wago_magescrolls')
ATT = os.path.join(HERE, 'fixtures', 'att')
OUT = os.path.join(ADDON, 'Data', 'MageScrollData.lua')


@pytest.fixture(scope='module')
def att():
    return att_data.load(ATT, items=False, dirs=build_magescrolls.ATT_DIRS)


@pytest.fixture(scope='module')
def data(att):
    return build_magescrolls.build([FIX], att)


def test_skill_scrolls_and_tiers(data):
    assert data['skill'] == 3012 and data['build'] == '1.60.1.99999'
    assert [(s['item'], s['rank'], s['tier']) for s in data['scrolls']] == [(9002, 1, 1), (61015, 1, 1), (9003, 15, 2)]
    # the "Comprehend Scroll" abilities in rank order: yellow and grey of each tier
    assert data['tiers'] == [{'rank': 1, 'yellow': 15, 'grey': 30, 'spell': 8101},
                             {'rank': 15, 'yellow': 50, 'grey': 75, 'spell': 8102}]


def test_helpers_charm_conjure_boost_bundle(data):
    assert data['charm'] == 69500 and data['conjure'] == 8200
    assert data['boost'] == 9011 and data['boostSpell'] == 8011, 'the use spell raises the Comprehension skill'
    assert data['bundle'] == 9030 and data['study'] == 8103, 'what Study makes'
    assert data['names'] == {'charm': 'Comprehension Charm', 'boost': 'Scroll of Comprehension', 'bundle': 'Bundle of Scrolls',
                             'conjure': 'Conjure Comprehension Charms'}
    assert [(a['spell'], a['name']) for a in data['abilities']] == [(8103, 'Study')]
    assert data['abilities'][0]['text'].endswith('Requires a suitable library.')


def test_results_mage_only_consumable_scrolls(data):
    got = [(r['item'], r['level'], r['spell']) for r in data['results']]
    assert got == [(9024, 12, 0), (9020, 16, 8020)], 'not the raid item, not for everyone, not armour, not the helpers'
    imbue = data['results'][1]
    assert imbue['name'] == 'Scroll of Imbue Test'
    assert imbue['text'] == 'Imbue a staff with magic for 60 min, increasing damage by up to 8.', imbue['text']


def test_sources_from_allthethings(data):
    assert data['att'] is None or isinstance(data['att'], str)
    world = {s['item']: s['world'] for s in data['scrolls']}
    assert world == {61015: True, 9002: False, 9003: False}
    assert [(b['quest'], b['item'], b['faction'], b['maps'], b['charm']) for b in data['books']] == [
        (78501, 69501, '', [1426], True), (78502, 69502, 'A', [1455, 1426], True)]
    assert data['friends'] == [{'quest': 78503, 'need': 2, 'level': 20, 'name': 'Friend of the Fixture', 'rewards': [69503]}]
    assert data['librarians'] == [
        {'npc': 81501, 'faction': 'A', 'map': 1455, 'x': 4900, 'y': 8640, 'name': 'Fixture Librarian'},
        {'npc': 81502, 'faction': 'H', 'map': 1426, 'x': 7360, 'y': 3300, 'name': 'Other Librarian'}]


def test_without_allthethings_no_sources():
    d = build_magescrolls.build([FIX], None)
    assert d['books'] == [] and d['librarians'] == [] and not any(s.get('world') for s in d['scrolls'])
    assert len(d['scrolls']) == 3


def test_lua_output_lazy_and_valid(data):
    lua = build_magescrolls.render_lua(data, built='2026-10-07')
    assert lua.startswith('-- Generated by tools/build_magescrolls.py')
    assert 'ns.LazyData("MAGESCROLLS", [=[\nreturn {\n' in lua and lua.rstrip().endswith(']=], 3)')
    assert lua_data.compact('{ 61015, 1, 1, 10, 1, "Scroll: AAA" },') in lua
    assert lua_data.compact('{ 78502, 69502, "A", { 1455, 1426 }, "An Alliance Tome", 1 },') in lua
    lupa = pytest.importorskip('lupa.lua51')
    t = lua_data.load(lua, 'MageScrollData.lua', lupa.LuaRuntime(unpack_returned_tuples=True)).MAGESCROLLS
    assert t.skill == 3012 and t.charm == 69500 and t.tiers[2][3] == 75 and t.scrolls[3][1] == 9003
    assert t.librarians[1][6] == 'Fixture Librarian' and t.friends[1][2] == 2


def test_missing_table_fails_clearly(tmp_path):
    with pytest.raises(SystemExit) as e:
        build_magescrolls.build([str(tmp_path)])
    assert 'ItemSparse' in str(e.value)


def test_empty_file_loads():
    lupa = pytest.importorskip('lupa.lua51')
    lua = build_magescrolls.render_lua(build_magescrolls.empty_data(), built='x')
    t = lua_data.load(lua, 'MageScrollData.lua', lupa.LuaRuntime(unpack_returned_tuples=True)).MAGESCROLLS
    assert t.skill == 0 and len(list(t.scrolls.keys())) == 0


def test_shipped_data_file_in_toc_and_valid():
    with open(os.path.join(ADDON, 'Amisia.toc'), encoding='utf-8') as fh:
        toc = fh.read()
    assert 'Data\\MageScrollData.lua [AllowLoadGameType camelot]' in toc
    assert toc.index('Data\\MageScrollData.lua') < toc.index('Gear\\MageScrolls.lua') < toc.index('UI\\Pages\\MageScrolls.lua')
    with open(OUT, encoding='utf-8') as fh:
        src = fh.read()
    assert src.startswith('-- Generated by tools/build_magescrolls.py')
    lupa = pytest.importorskip('lupa.lua51')
    t = lua_data.load(src, 'MageScrollData.lua', lupa.LuaRuntime(unpack_returned_tuples=True)).MAGESCROLLS
    n = int(src.rsplit(', ', 1)[1].rstrip(')\n'))
    assert n == len(list(t.scrolls.keys())), 'the count is the number of scrolls'
    for _, s in t.scrolls.items():
        assert s[2] >= 1 and 1 <= s[3] <= len(list(t.tiers.keys()))


@pytest.mark.skipif(not (os.path.isdir(build_magescrolls.WAGO) and os.path.exists(os.path.join(att_data.ATT_CACHE, 'COMMIT'))),
                    reason='needs the client tables and the AllTheThings download')
def test_shipped_file_is_current():
    dirs = [build_magescrolls.WAGO]
    if build_magescrolls.find_table(dirs, 'ItemSparse') is None:
        pytest.skip('no client tables')
    att = att_data.load(att_data.ATT_CACHE, items=False, dirs=build_magescrolls.ATT_DIRS)
    with open(OUT, encoding='utf-8') as fh:
        shipped = fh.read()
    import re
    built = re.search(r'built\s*=\s*"([^"]*)"', shipped).group(1)
    assert build_magescrolls.render_lua(build_magescrolls.build(dirs, att), built=built) == shipped, \
        'rebuild: python3 tools/build_magescrolls.py'
