-- GENERATED by tools/build_bis.py. Do not edit; rebuild instead.
-- Amisia's own weights for TBC Anniversary at level 70 (OWN_TBC in tools/build_bis.py); no
-- weights of anyone else are used. Shared under the licence of the addon.
local _, ns = ...
if ns.IsForever and ns.IsForever() then return end

-- Hit, crit, haste, expertise, dodge, parry and block weights are per percent, DEF per defence point,
-- GEM and META per socket, the rest per point. OHDPS is the share of off-hand weapon damage that
-- counts; unit names the stat one point of score is worth.
ns.GEAR_WEIGHTS = {
    brackets = {70},
    order = {"WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST", "SHAMAN", "MAGE", "WARLOCK", "DRUID"},
    specs = {
        WARRIOR = {
            { key = "dps", name = "Waffen/Furor", role = "dps",
              all = {AGI = 1, AP = 1, CRIT = 29, DPS = 14, EXP = 25, GEM = 16, HASTE = 19, HIT = 24, META = 30, OHDPS = 0.5, STA = 0.05, STR = 2, unit = "AP"} },
            { key = "tank", name = "Schutz", role = "tank",
              all = {AGI = 0.6, AP = 0.1, ARMOR = 0.06, BLOCK = 6, BLOCKVAL = 0.5, DEF = 2, DODGE = 18, DPS = 3, EXP = 10, GEM = 12, HIT = 8, META = 20, PARRY = 15, STA = 1, STR = 0.4, unit = "STA"} },
        },
        PALADIN = {
            { key = "holy", name = "Heilig", role = "heal",
              all = {GEM = 18, HEAL = 1, INT = 1.1, META = 20, MP5 = 2, SCRIT = 14, SHASTE = 10, SPI = 0.1, STA = 0.1, unit = "HEAL"} },
            { key = "tank", name = "Schutz", role = "tank",
              all = {AGI = 0.5, ARMOR = 0.06, BLOCK = 8, BLOCKVAL = 0.6, DEF = 2, DODGE = 18, DPS = 1, EXP = 6, GEM = 12, HIT = 6, INT = 0.3, META = 20, MP5 = 1, PARRY = 15, SP = 0.6, STA = 1, unit = "STA"} },
            { key = "ret", name = "Vergeltung", role = "dps",
              all = {AGI = 0.9, AP = 1, CRIT = 22, DPS = 14, EXP = 22, GEM = 18, HASTE = 15, HIT = 25, INT = 0.3, META = 30, MP5 = 1, SP = 0.4, STR = 2.2, unit = "AP"} },
        },
        HUNTER = {
            { key = "dps", name = "Jäger", role = "dps",
              all = {AGI = 1.6, AP = 1, CRIT = 22, DPS = 0.5, GEM = 13, HASTE = 18, HIT = 25, INT = 0.4, META = 30, MP5 = 1.5, RAP = 1, RDPS = 14, unit = "AP"} },
        },
        ROGUE = {
            { key = "dps", name = "Schurke", role = "dps",
              all = {AGI = 1.8, AP = 1, CRIT = 22, DPS = 14, EXP = 25, GEM = 14, HASTE = 19, HIT = 25, META = 30, OHDPS = 0.5, STA = 0.05, STR = 1.1, unit = "AP"} },
        },
        PRIEST = {
            { key = "holy", name = "Heilig/Disziplin", role = "heal",
              all = {GEM = 18, HEAL = 1, INT = 0.8, META = 20, MP5 = 2, SCRIT = 8, SHASTE = 12, SPI = 0.8, STA = 0.1, unit = "HEAL"} },
            { key = "shadow", name = "Schatten", role = "dps",
              all = {GEM = 9, INT = 0.2, META = 20, MP5 = 0.8, SCRIT = 8, SHASTE = 12, SHIT = 14, SP = 1, SPI = 0.15, SP_SHADOW = 1, STA = 0.05, unit = "SP"} },
        },
        SHAMAN = {
            { key = "ele", name = "Elementar", role = "dps",
              all = {GEM = 9, INT = 0.3, META = 20, MP5 = 0.8, SCRIT = 13, SHASTE = 12, SHIT = 14, SP = 1, SP_NATURE = 1, unit = "SP"} },
            { key = "enh", name = "Verstärkung", role = "dps",
              all = {AGI = 0.9, AP = 1, CRIT = 22, DPS = 14, EXP = 25, GEM = 16, HASTE = 20, HIT = 25, INT = 0.3, META = 30, MP5 = 1, OHDPS = 0.5, STR = 2, unit = "AP"} },
            { key = "resto", name = "Wiederherstellung", role = "heal",
              all = {GEM = 18, HEAL = 1, INT = 0.8, META = 20, MP5 = 2.2, SCRIT = 10, SHASTE = 14, SPI = 0.2, STA = 0.1, unit = "HEAL"} },
        },
        MAGE = {
            { key = "arcane", name = "Arkan", role = "dps",
              all = {GEM = 9, INT = 0.7, META = 20, MP5 = 0.5, SCRIT = 11, SHASTE = 13, SHIT = 14, SP = 1, SPI = 0.3, SP_ARCANE = 1, unit = "SP"} },
            { key = "fire", name = "Feuer", role = "dps",
              all = {GEM = 9, INT = 0.4, META = 20, MP5 = 0.5, SCRIT = 11, SHASTE = 13, SHIT = 14, SP = 1, SPI = 0.2, SP_FIRE = 1, unit = "SP"} },
            { key = "frost", name = "Frost", role = "dps",
              all = {GEM = 9, INT = 0.4, META = 20, MP5 = 0.5, SCRIT = 11, SHASTE = 13, SHIT = 14, SP = 1, SPI = 0.2, SP_FROST = 1, unit = "SP"} },
        },
        WARLOCK = {
            { key = "affli", name = "Gebrechen", role = "dps",
              all = {GEM = 9, INT = 0.2, META = 20, SCRIT = 5, SHASTE = 12, SHIT = 15, SP = 1, SPI = 0.2, SP_SHADOW = 1, STA = 0.1, unit = "SP"} },
            { key = "destro", name = "Zerstörung", role = "dps",
              all = {GEM = 9, INT = 0.2, META = 20, SCRIT = 13, SHASTE = 12, SHIT = 15, SP = 1, SPI = 0.1, SP_FIRE = 0.3, SP_SHADOW = 1, STA = 0.1, unit = "SP"} },
        },
        DRUID = {
            { key = "balance", name = "Gleichgewicht", role = "dps",
              all = {GEM = 9, INT = 0.4, META = 20, MP5 = 0.6, SCRIT = 11, SHASTE = 12, SHIT = 14, SP = 1, SPI = 0.2, SP_ARCANE = 0.6, SP_NATURE = 0.4, unit = "SP"} },
            { key = "feral", name = "Wilder Kampf (Katze)", role = "dps",
              all = {AGI = 2, AP = 1, CRIT = 22, EXP = 25, GEM = 16, HASTE = 10, HIT = 25, META = 30, STR = 2.2, unit = "AP"} },
            { key = "bear", name = "Bär", role = "tank",
              all = {AGI = 1, AP = 0.1, ARMOR = 0.1, CRIT = 3, DEF = 1, DODGE = 15, EXP = 8, GEM = 12, HIT = 6, META = 20, STA = 1, STR = 0.4, unit = "STA"} },
            { key = "resto", name = "Wiederherstellung", role = "heal",
              all = {GEM = 18, HEAL = 1, INT = 0.8, META = 20, MP5 = 1.6, SCRIT = 4, SHASTE = 12, SPI = 0.9, STA = 0.1, unit = "HEAL"} },
        },
    },
}
