-- GENERATED by tools/build_dungeons.py from tools/forever_dungeons.json. Do not edit; rebuild instead.
-- Facts only (names, level ranges, sizes, bosses known so far, opening dates), checked by hand on 2026-10-05;
-- the sources of every entry are named in the JSON file. Classic dungeons have no level range until
-- the client's LFGDungeons table is read; the planner estimates one from their items meanwhile.
local _, ns = ...

ns.DUNGEON_FACTS = {
    checked = "2026-10-05",
    list = {
        { key = "rfc", name = "Ragefire Chasm", kind = "party" },
        { key = "wc", name = "Wailing Caverns", kind = "party" },
        { key = "deadmines", name = "The Deadmines", kind = "party" },
        { key = "thanes", name = "Hall of Thanes", kind = "party", min = 13, max = 18, bosses = { "Faldrim Anvilmar", "Magmatus", "Plunder", "Durgen Dirgehammer" } },
        { key = "sfk", name = "Shadowfang Keep", kind = "party" },
        { key = "lordaeron", name = "Ruins of Lordaeron", kind = "party", min = 15, max = 20, bosses = { "The Baron", "Witherfang", "The Abandoned", "Bjork", "Rath'mael", "Viktor the Vile" } },
        { key = "bfd", name = "Blackfathom Deeps", kind = "party" },
        { key = "stockade", name = "The Stockade", kind = "party" },
        { key = "gnomer", name = "Gnomeregan", kind = "party" },
        { key = "rfk", name = "Razorfen Kraul", kind = "party" },
        { key = "excavation", name = "Excavation Site", kind = "party", min = 26, max = 31, aliases = { "Excavation Site: Wetlands" } },
        { key = "dalaran", name = "City of Dalaran", kind = "party", min = 28, max = 33 },
        { key = "sm", name = "Scarlet Monastery", kind = "party", aliases = { "Scarlet Monastery - Graveyard", "Scarlet Monastery - Library", "Scarlet Monastery - Armory", "Scarlet Monastery - Cathedral", "Scarlet Monastery: Graveyard" } },
        { key = "rfd", name = "Razorfen Downs", kind = "party" },
        { key = "drowned", name = "Drowned City", kind = "party", min = 35, max = 40 },
        { key = "ulda", name = "Uldaman", kind = "party" },
        { key = "kroldok", name = "Krol'dok Stronghold", kind = "party", min = 40, max = 45 },
        { key = "zf", name = "Zul'Farrak", kind = "party" },
        { key = "mara", name = "Maraudon", kind = "party" },
        { key = "alcaz", name = "Alcaz Prison", kind = "party", min = 48, max = 53 },
        { key = "brd", name = "Blackrock Depths", kind = "party" },
        { key = "blackmaw", name = "Blackmaw Hold", kind = "party", min = 55, max = 60 },
        { key = "lbrs", name = "Lower Blackrock Spire", kind = "party", aliases = { "Blackrock Spire" }, part = "Blackrock Spire" },
        { key = "ubrs", name = "Upper Blackrock Spire", kind = "party", part = "Blackrock Spire" },
        { key = "dire", name = "Dire Maul", kind = "party" },
        { key = "scholo", name = "Scholomance", kind = "party" },
        { key = "strat", name = "Stratholme", kind = "party" },
        { key = "shaper", name = "Shaper's Terrace", kind = "party", min = 58, max = 60 },
        { key = "barrow", name = "Barrow Deeps", kind = "raid", size = 10, from = "2026-12-09" },
        { key = "hyjal", name = "Hyjal Summit", kind = "raid", size = 20, from = "2026-12-09" },
        { key = "onyxia", name = "Onyxia's Lair", kind = "raid", size = 40, inst = 249, area = 2159, from = "2026-12-09" },
    },
}
