"""Builds addon/Amisia/DungeonData.lua from tools/forever_dungeons.json: the dungeons and raids of
WoW Forever for the addon's dungeon planner (Dungeons.lua).

The JSON file is kept by hand and holds facts only (names, level ranges, sizes, bosses known so
far, opening dates, instance ids), each entry with its source ("src", and "<field>_src" for a field
that comes from elsewhere, as boss lists read from the repo's item data); see its "sources" block.
Nothing is fetched. Run it after changing the JSON:

    python tools/build_dungeons.py

The generated table is ns.DUNGEON_FACTS. Once tools/build_bis.py writes ns.BIS.DG (task 2 of the
2.3 design: the same facts plus the level ranges of the client's LFGDungeons table and the bosses'
NPC ids), the planner takes that instead and this file can go.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FACTS = os.path.join(HERE, 'forever_dungeons.json')
OUT = os.path.join(ROOT, 'addon', 'Amisia', 'DungeonData.lua')

# Field order in the Lua table; anything else in the JSON (src and the <field>_src labels) is not
# written. part: the client's name of an instance that hosts several dungeons (Blackrock Spire).
FIELDS = ('key', 'name', 'kind', 'min', 'max', 'size', 'inst', 'area', 'from', 'bosses', 'aliases', 'part')


def lua_str(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def lua_val(v):
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return '{ ' + ', '.join(lua_val(x) for x in v) + ' }'
    return lua_str(v)


def lua_key(k):
    # "from" is no Lua keyword, but a bracketed key reads the same in every Lua
    return k if k.isidentifier() else '[' + lua_str(k) + ']'


def render(facts):
    """The Lua file for the facts, always the same text for the same input."""
    lines = [
        '-- GENERATED by tools/build_dungeons.py from tools/forever_dungeons.json. Do not edit; rebuild instead.',
        '-- Facts only (names, level ranges, sizes, bosses known so far, opening dates), checked by hand on '
        + facts['checked'] + ';',
        '-- the sources of every entry are named in the JSON file. Classic dungeons have no level range until',
        "-- the client's LFGDungeons table is read; the planner estimates one from their items meanwhile.",
        'local _, ns = ...',
        '',
        'ns.DUNGEON_FACTS = {',
        '    checked = ' + lua_str(facts['checked']) + ',',
        '    list = {',
    ]
    for e in facts['dungeons']:
        parts = []
        for k in FIELDS:
            v = e.get(k)
            if v is None or v == []:
                continue
            parts.append(lua_key(k) + ' = ' + lua_val(v))
        lines.append('        { ' + ', '.join(parts) + ' },')
    lines += ['    },', '}', '']
    return '\n'.join(lines)


def main(argv):
    with open(FACTS, encoding='utf-8') as fh:
        facts = json.load(fh)
    text = render(facts)
    old = None
    if os.path.exists(OUT):
        with open(OUT, encoding='utf-8') as fh:
            old = fh.read()
    if old == text:
        print('DungeonData.lua is current (%d entries)' % len(facts['dungeons']))
        return 0
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print('wrote %s (%d entries)' % (os.path.relpath(OUT, ROOT), len(facts['dungeons'])))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
