"""Builds addon/Amisia/DungeonArt.lua: the client's own loading screen per dungeon, for the header
image of the dungeon planner. Game data only (file data ids of the client's art), no image is
copied into the addon: the client draws its own file.

The client table Map gives every instance its LoadingScreenID, the table LoadingScreens the file:
NarrowScreenFileDataID for the old dungeons (a 4:3 picture stored as a square texture, kind "n"),
MainImageFileDataID for Forever's own screens (wide, 2992 x 1684 with empty bands above and below,
kind "w"). The instance ids come from the dungeon facts (tools/forever_dungeons.json with the
client values of tools/forever_dungeons_client.json, as build_dungeons.py merges them). A dungeon
without an instance id or a file takes the general screen of its kind at runtime (party: the
client's general dungeon screen, raid: its raid screen, both used by rows of its Map table).

With --wago the tables are read (default folders ~/addons/_wago, then ~/addons/_cache/wago; of
each table the first folder that has one counts) and the result is kept in
tools/forever_dungeon_art.json; without it that file is rendered as it is. The tables come from
wago.tools (CSV of the Forever build) or tools/export_db2.ps1 -Tables Map,LoadingScreens.
"""
import argparse
import csv
import json
import os
import re
import sys

import att_data
import build_dungeons

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SNAPSHOT = os.path.join(HERE, 'forever_dungeon_art.json')
OUT = os.path.join(ROOT, 'addon', 'Amisia', 'DungeonArt.lua')
WAGO_DIRS = (os.path.expanduser('~/addons/_wago'), os.path.expanduser('~/addons/_cache/wago'))

# The general screens of the client's LoadingScreens table (LoadScreenDungeon, LoadScreenRaid).
FALLBACK_SCREENS = {'party': 23, 'raid': 61}


def _int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _table(table, dirs):
    """(file name, rows) of the first folder that has the table, else (None, [])."""
    for d in dirs:
        path = att_data.wago_csv(d, table)
        if path:
            with open(path, encoding='utf-8-sig') as fh:
                return os.path.basename(path), list(csv.DictReader(fh))
    return None, []


def _screen(row):
    """[file id, kind] of a LoadingScreens row, or None without a file."""
    if not row:
        return None
    main, narrow = _int(row.get('MainImageFileDataID')), _int(row.get('NarrowScreenFileDataID'))
    if main > 0:
        return [main, 'w']
    if narrow > 0:
        return [narrow, 'n']
    return None


def client_art(facts, dirs=WAGO_DIRS):
    """{'build', 'tables', 'dungeons': {key: [file id, kind]}, 'party', 'raid'} from the client
    tables Map and LoadingScreens for the facts (list of dicts with key and inst)."""
    map_name, maps = _table('Map', dirs)
    ls_name, screens = _table('LoadingScreens', dirs)
    tables = {}
    if map_name:
        tables['Map'] = map_name
    if ls_name:
        tables['LoadingScreens'] = ls_name
    build = None
    for name in (map_name, ls_name):
        m = name and re.match(r'^[A-Za-z]+\.(\d+(?:\.\d+)+)\.csv$', name)
        if m:
            build = m.group(1)
            break
    by_screen = {_int(r.get('ID')): r for r in screens}
    screen_of_map = {_int(r.get('ID')): _int(r.get('LoadingScreenID')) for r in maps}
    used = set(screen_of_map.values())
    out = {}
    for e in facts:
        inst = e.get('inst')
        if not inst or inst not in screen_of_map:
            continue
        art = _screen(by_screen.get(screen_of_map[inst]))
        if art:
            out[e['key']] = art
    art = {'build': build, 'tables': tables, 'dungeons': out}
    for kind, sid in FALLBACK_SCREENS.items():
        art[kind] = _screen(by_screen.get(sid)) if sid in used else None
    return art


def render(art):
    lines = [
        '-- GENERATED by tools/build_dungeonart.py from the client tables Map and LoadingScreens',
        '-- (build %s, kept in tools/forever_dungeon_art.json). Do not edit; rebuild instead.' % (art.get('build') or '?'),
        "-- The client's own loading screen of every dungeon by its key: { file data id, kind }, kind \"n\" a",
        '-- 4:3 picture stored as a square texture, "w" a wide one with empty bands above and below. party',
        '-- and raid: the general screens for a dungeon without its own.',
        'local _, ns = ...',
        '',
        'ns.DUNGEON_ART = {',
        '    build = "%s",' % (art.get('build') or ''),
    ]
    for kind in ('party', 'raid'):
        v = art.get(kind)
        if v:
            lines.append('    %s = { %d, "%s" },' % (kind, v[0], v[1]))
    lines.append('    D = {')
    for key in sorted(art.get('dungeons') or {}):
        fid, kind = art['dungeons'][key]
        lines.append('        %s = { %d, "%s" },' % (key, fid, kind))
    lines.append('    },')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def load_facts():
    with open(build_dungeons.FACTS, encoding='utf-8') as fh:
        facts = json.load(fh)
    return build_dungeons.merge(facts, build_dungeons.load_client())


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--wago', nargs='*', default=None,
                    help='read the client tables first (default folders: ~/addons/_wago, then ~/addons/_cache/wago)')
    args = ap.parse_args(argv)
    if args.wago is not None:
        dirs = args.wago or WAGO_DIRS
        art = client_art(load_facts(), dirs)
        if set(art['tables']) != {'Map', 'LoadingScreens'}:
            raise SystemExit('need the Map and LoadingScreens CSV in ' + ', '.join(dirs))
        print('client tables: ' + ', '.join(f'{t} {n}' for t, n in sorted(art['tables'].items())))
        missing = [e['key'] for e in load_facts() if e['key'] not in art['dungeons']]
        print('%d dungeons with their own screen; general screen for: %s' % (len(art['dungeons']), ', '.join(missing) or '-'))
        with open(SNAPSHOT, 'w', encoding='utf-8', newline='\n') as fh:
            json.dump(art, fh, indent=1, sort_keys=True)
            fh.write('\n')
    with open(SNAPSHOT, encoding='utf-8') as fh:
        art = json.load(fh)
    text = render(art)
    old = None
    if os.path.exists(OUT):
        with open(OUT, encoding='utf-8') as fh:
            old = fh.read()
    if old == text:
        print('DungeonArt.lua is current')
        return 0
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print('wrote %s (%d dungeons)' % (os.path.relpath(OUT, ROOT), len(art['dungeons'])))
    return 0


if __name__ == '__main__':
    sys.exit(main())
