-- GENERATED by tools/build_dungeonart.py from the client tables Map and LoadingScreens
-- (build 1.60.1.70338, kept in tools/forever_dungeon_art.json). Do not edit; rebuild instead.
-- The client's own loading screen of every dungeon by its key: { file data id, kind }, kind "n" a
-- 4:3 picture stored as a square texture, "w" a wide one with empty bands above and below. party
-- and raid: the general screens for a dungeon without its own.
local _, ns = ...

ns.DUNGEON_ART = {
    build = "1.60.1.70338",
    party = { 131838, "n" },
    raid = { 131863, "n" },
    D = {
        bfd = { 131823, "n" },
        brd = { 131824, "n" },
        dalaran = { 7963775, "w" },
        deadmines = { 131833, "n" },
        dire = { 131835, "n" },
        excavation = { 7963777, "w" },
        gnomer = { 131841, "n" },
        lbrs = { 131825, "n" },
        lordaeron = { 7963782, "w" },
        mara = { 131850, "n" },
        onyxia = { 131863, "n" },
        rfc = { 131862, "n" },
        rfd = { 131864, "n" },
        rfk = { 131865, "n" },
        scholo = { 131868, "n" },
        sfk = { 131869, "n" },
        sm = { 131852, "n" },
        stockade = { 131870, "n" },
        strat = { 131871, "n" },
        thanes = { 7963781, "w" },
        ubrs = { 131825, "n" },
        ulda = { 131876, "n" },
        wc = { 131882, "n" },
        zf = { 131885, "n" },
    },
}
