-- GENERATED by tools/build_dungeons.py from tools/forever_dungeons.json and
-- tools/forever_dungeons_client.json. Do not edit; rebuild instead.
-- Facts only (names, level ranges, sizes, bosses known so far, opening dates), checked by hand on 2026-10-05;
-- the sources of every entry are named in the JSON file. lvl is the level the client tunes a dungeon
-- to (its LFGDungeons and ContentTuning tables), the low end of its range; dungeons without a fact
-- range take the high end from their items meanwhile.
local _, ns = ...

ns.DUNGEON_FACTS = {
    checked = "2026-10-05",
    list = {
        { key = "rfc", name = "Ragefire Chasm", kind = "party", lvl = 13, inst = 389 },
        { key = "wc", name = "Wailing Caverns", kind = "party", lvl = 17, inst = 43 },
        { key = "deadmines", name = "The Deadmines", kind = "party", lvl = 16, inst = 36 },
        { key = "thanes", name = "Hall of Thanes", kind = "party", min = 13, max = 18, lvl = 13, inst = 3065, bosses = { "Faldrim Anvilmar", "Magmatus", "Plunder", "Durgen Dirgehammer" } },
        { key = "sfk", name = "Shadowfang Keep", kind = "party", lvl = 18, inst = 33 },
        { key = "lordaeron", name = "Ruins of Lordaeron", kind = "party", min = 15, max = 20, lvl = 15, inst = 2999, bosses = { "The Baron", "Witherfang", "The Abandoned", "Bjork", "Rath'mael", "Viktor the Vile" } },
        { key = "bfd", name = "Blackfathom Deeps", kind = "party", lvl = 22, inst = 48 },
        { key = "stockade", name = "The Stockade", kind = "party", lvl = 23, inst = 34 },
        { key = "gnomer", name = "Gnomeregan", kind = "party", lvl = 25, inst = 90 },
        { key = "rfk", name = "Razorfen Kraul", kind = "party", lvl = 24, inst = 47 },
        { key = "excavation", name = "Excavation Site", kind = "party", min = 26, max = 31, lvl = 26, inst = 2998, aliases = { "Excavation Site: Wetlands" } },
        { key = "dalaran", name = "City of Dalaran", kind = "party", min = 28, max = 33, lvl = 28, inst = 2959 },
        { key = "sm", name = "Scarlet Monastery", kind = "party", lvl = 30, inst = 189, aliases = { "Scarlet Monastery - Graveyard", "Scarlet Monastery - Library", "Scarlet Monastery - Armory", "Scarlet Monastery - Cathedral", "Scarlet Monastery: Graveyard" } },
        { key = "rfd", name = "Razorfen Downs", kind = "party", lvl = 34, inst = 129 },
        { key = "drowned", name = "Drowned City", kind = "party", min = 35, max = 40 },
        { key = "ulda", name = "Uldaman", kind = "party", lvl = 35, inst = 70 },
        { key = "kroldok", name = "Krol'dok Stronghold", kind = "party", min = 40, max = 45 },
        { key = "zf", name = "Zul'Farrak", kind = "party", lvl = 42, inst = 209 },
        { key = "mara", name = "Maraudon", kind = "party", lvl = 42, inst = 349 },
        { key = "alcaz", name = "Alcaz Prison", kind = "party", min = 48, max = 53 },
        { key = "brd", name = "Blackrock Depths", kind = "party", lvl = 48, inst = 230 },
        { key = "blackmaw", name = "Blackmaw Hold", kind = "party", min = 55, max = 60 },
        { key = "lbrs", name = "Lower Blackrock Spire", kind = "party", lvl = 53, inst = 229, aliases = { "Blackrock Spire" }, part = "Blackrock Spire" },
        { key = "ubrs", name = "Upper Blackrock Spire", kind = "party", lvl = 53, inst = 229, part = "Blackrock Spire" },
        { key = "dire", name = "Dire Maul", kind = "party", lvl = 54, inst = 429 },
        { key = "scholo", name = "Scholomance", kind = "party", lvl = 57, inst = 289 },
        { key = "strat", name = "Stratholme", kind = "party", lvl = 55, inst = 329 },
        { key = "shaper", name = "Shaper's Terrace", kind = "party", min = 58, max = 60 },
        { key = "barrow", name = "Barrow Deeps", kind = "raid", size = 10, from = "2026-12-09" },
        { key = "hyjal", name = "Hyjal Summit", kind = "raid", size = 20, from = "2026-12-09" },
        { key = "onyxia", name = "Onyxia's Lair", kind = "raid", lvl = 60, size = 40, inst = 249, area = 2159, from = "2026-12-09" },
    },
}
